<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\AIpoweredVivaExamSystem.Application\AIpoweredVivaExamSystem.Application.csproj" />
    <ProjectReference Include="..\AIpoweredVivaExamSystem.Persistence\AIpoweredVivaExamSystem.Persistence.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
